spring.application.name=cms
spring.datasource.url=jdbc:postgresql://localhost:5432/MSI
spring.datasource.username=scut
spring.datasource.password=scut


spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
